# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'vagrant-openstack-provider'

Vagrant.configure("2") do |config|
    config.ssh.username = 'ubuntu'
    config.ssh.private_key_path = "./linux.pem"
    config.vm.provider :openstack do |os, override |
      os.identity_api_version = '3'
      os.openstack_auth_url = 'http://10.28.3.240:5000/v3'
      os.domain_name = 'fundacion-jala'
      os.username = <user name>
      os.password = <password name>
      os.tenant_name = 'e92ea25c88ea4fdb8bf1624a78732e6c'
      os.project_name  = 'fj_rogeralvarez_at08-desktop'
      os.keypair_name   = 'linux'
      os.image = 'ubuntu-18.04-amd64-mate_desktop_19122018'
      os.flavor = 'f2.desktop.large'
      os.server_name = 'RALVAREZM-DH03'
      override.vm.synced_folder '.', '/vagrant', disabled:true
  end
end